### PR TITLE
cache compiled result

### PR DESCRIPTION
**Pull request by lingyan**
Optimize performance by caching the compiled route paths.

@mridgway  cc: @jasisk

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
:+1:

**Comment by mridgway** [comment]
:+1:

**Comment by lingyan** [comment]
Minor change (added routePath to error message on https://github.com/yahoo/routr/pull/26/files#diff-504fd89f344be1e9c4b583f3ebd7428aL153)

**Pull request merged**
