### PR TITLE
fix handling of array like query params

### PR DESCRIPTION
**Pull request by pablopalacios**
- [x] add more test cases
- [x] fix lint errors
- [x] make it clear what is the current standard for `?hello` case

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by pablopalacios** [comment]
@redonkulus I've took the test from `fluxible-router`, added it here and applied the fixes. However, there is one thing that seems to not be fixable, or at least not with the current implementation:

`query-string` parses `?hello` to `{ hello: null }` while native `URLSearchParams` will parse it to `{ hello: '' }`. `query-string` uses as an outdated spec as reference: https://www.w3.org/TR/2012/WD-url-20120524/#collect-url-parameters. 

So far, I haven't found any reference regarding `URLSearchParams` behavior in the newer specs. But, as first impression, I would say that `URLSearchParams` should be taken as reference (since it is part of the spec and I don't think that both chrome and firefox would have implemented it wrongly). But I still want to find the reason behind it...

**Comment by pablopalacios** [comment]
So, today I went deep on the specs to understand how things should be. Here is a summary:

- `query-string` parses `?hello` into `{ hello: null }` as seen [here](https://github.com/sindresorhus/query-string/blob/b03e2e709664834e6cdcf50cd84b0056cdb5b7ff/index.js#L293);
- The reference is an outdated [W3C working draft](https://www.w3.org/TR/2012/WD-url-20120524/#collect-url-parameters) from 2012 which clearly states how to deal with this specific case;
- In 2014, [another WD](https://www.w3.org/TR/2014/WD-url-1-20141209/) was published and the reference used by `query-string` was removed. It presents for the first time the `URLSearchParams` interface, and states that it should use `application/x-www-form-urlencoded` parser to handle a query string. The specification says that in the absence of an equal sign, the value should be an empty string. But this WD is also outdated;
- In 2016, a [final note](https://www.w3.org/TR/url-1/) was published, stating that the work has been discontinued and that this standard should not be taken as reference for any implementation. Instead, the [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) and [RFC 3987](https://datatracker.ietf.org/doc/html/rfc3987) and the [WHATWG URL spec](https://url.spec.whatwg.org/) should be used instead;
- RFC 3986 doesn't specify a syntax for query strings. Actually, as far as I got, this thing of using key/value pairs separated by a `&` is more like a convention than a standard ([see here](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4)).
- RFC 3987, roughly saying, only concerns about extending the URL spec to cover non ASCII characters, so nothing much related to query strings there.
- The WHATWG document, however, specifies that `URLSearchParams` should use `application/x-www-form-urlencoded` parser  just as specified in the WD of 2014 ([see sub-step 2 of step 3 of the initializer interface](https://url.spec.whatwg.org/#interface-urlsearchparams)). It's then clear that the case `?hello` should become `{ hello: '' }` ([see sub-step 3 of step 3 here](https://url.spec.whatwg.org/#urlencoded-parsing)) since whenever no `=` is present, the value should be an empty string.

**Comment by redonkulus** [comment]
Wow great research. Looks like empty string is the way to go. Thanks digging into this!

**Comment by pablopalacios** [comment]
Then it's done :). I just fixed the case with arrays. Before it was parsing `?a=1&a=2` in `{ a: '1' }` instead of `{ a: ['1', '2'] }`.

**Review by redonkulus — APPROVED** [review]

**Pull request merged**
