### PR TITLE
Fix decodeURIComponent of undefined bug

### PR DESCRIPTION
**Pull request by janus-toendering**
decodeURIComponent(undefined) returns 'undefined' which sets
all optional parameters that are not present in the url to the
string value 'undefined'.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Seems ok to me 👍

**Comment by lingyan** [comment]
@gigabo Could you please also review this?  Thanks!

**Comment by lingyan** [comment]
👍

**Comment by gigabo** [comment]
Makes sense.  Nice fix @janus-toendering. 👍

**Comment by redonkulus** [comment]
@janus-toendering thanks!

**Comment by redonkulus** [comment]
released in version 2.0.1

**Comment by janus-toendering** [comment]
You're welcome. And thank you for routr and friends :-)

**Comment by lingyan** [comment]
thanks @janus-toendering @gigabo

**Pull request merged**
